import { createSlice } from "@reduxjs/toolkit";

// var APIurl = "https://bos.beyondexs.com/api/"
// var baseurl = "https://bos.beyondexs.com/"

var APIurl = "https://bosuat.beyondexs.com/api/"
var baseurl = "https://bosuat.beyondexs.com/"
// var APIurl ="https://dvmtapi.bexatm.com/hr/api/"
// var baseurl = "https://dvmtapi.bexatm.com/"

// var APIurl = "https://phpmigrationapi.bexatm.com/hr/api/"
// var baseurl = "https://phpmigrationapi.bexatm.com/"

 const initialState = {  
//hr
baseApiUrl: APIurl,
baseUrl: baseurl,
listViewurl: APIurl + 'wslistview_mysql.php',
loginUrl:APIurl + 'LController.php',
authUrl:APIurl + 'auth.php',
comboUrl:APIurl + 'APIController.php',
apiUrl :APIurl + 'APIController.php',
imgUploadUrl:baseurl + 'imgup.php',
compdetailPostUrl:APIurl + 'CompanypostController.php',
//imgUploadUrl:baseurl + 'imgup6.php',
imageUrl:baseurl + 'uploads/images/',
imageNameUpdateUrl:APIurl + 'CMController.php',
//attachmentUrl:baseurl + 'uploads/images/',
attachmentUrl:baseurl + 'uploads/images/',
attachmentSkilUrl:baseurl + 'uploads/attachments/',
fileUploadUrl:baseurl + 'fileupload.php',
pcdurl:APIurl + 'PCDController.php',
pdfurl:baseurl + 'tcpdf/',
indentUrl:APIurl + 'IndentController.php',
invoiceUrl:APIurl + 'InvoiceController.php',
commonUrl : APIurl + 'CommonController.php',
bomCopyUrl: APIurl + 'VersioningController.php',
bomHeaderUrl: APIurl + 'BOMController.php',
stockUrl:APIurl + 'StockController.php',
batchUrl:APIurl + 'BatchstructureController.php',
finalinvUrl:APIurl + 'FinalInvoiceController.php',
proformainvUrl:APIurl + 'ProfoinvoiceController.php',
orderUrl:APIurl + 'CustomerOrder.php',
stockReqUrl:APIurl + 'StockRequirement.php',
productUrl:APIurl + 'StockProcedure.php',
bomLkUrl:APIurl + 'BOMLeatherCountController.php',
designPUrl:APIurl + 'UomconversiongetController.php',
costingMatrialUrl:APIurl + 'BomcostController.php?',
conversionUrl:APIurl + 'UomconversiongetController.php',
userGroupUrl:APIurl + 'GroupaccessController.php',
dcTrackingUrl:APIurl + 'DctrackingController.php',
trackingUrl:APIurl + 'MaterialtrackingController.php',
supplierTrackUrl:APIurl + 'SuppliertrackingController.php',
materialsTrackingUrl:APIurl + 'MaterialTrackingChart.php',
supplytrackingUrl:APIurl + 'SupplierTrackingChart.php',
producttrackingUrl:APIurl + 'ProductpriceController.php?',
customerorderanalysisUrl:APIurl + 'CustomerOrderChart.php?',
prductorderanalysisUrl:APIurl + 'ProductOrderChart.php?',
mailContentGeturl:APIurl + 'EmailController.php',
mailSendUrl:APIurl + 'invoicemail.php',
materialUomCovUrl:APIurl + 'MaterialUOMConversionController.php',
decryptUrl:APIurl + 'HashtokenController.php',
costingLeatherUrl:APIurl + 'BomLeathercost.php',
customerLeatherUrl:APIurl + 'CustomerLeatherController.php',
getempdeploymentUrl:APIurl + 'getempdeployment.php?',
postempdeployment:APIurl + 'postempdeployment.php?',
matProcurementUrl:APIurl + 'MaterialProcurementChart.php',
stockorderUrl:APIurl + 'MaterialOrderReportController.php',
dcsummaryUrl:APIurl + 'getdcsummary.php',
dcpostsummaryUrl:APIurl + 'postdcsummary.php',
packinglistCbmUrl:APIurl + 'CbmCalculation.php',
searchUrl:APIurl + 'productSearch3.php',
// searchUrl:'http://localhost:8080/MYPROJECT/bgems-api/productSearch.php',
jobworkbomurl:APIurl + 'JobworkController.php',
alterNateMaterial:APIurl + 'AlterMaterialController.php',
PurchaseOrderParameterUrl:APIurl + 'APIController.php',
PurchaseorderratingUrl:APIurl + 'ParametergetController.php',
CustomerPriceorderQtyUrl:APIurl + 'InternalorderController.php',
apiweightageUrl:APIurl + 'HRWeightagesGetContoller.php',
weightagepostUrl:APIurl + 'HRWeightagesContoller.php',
employeeattendanceUrl:APIurl + "getempattendancehistory.php",
payrollattendanceUrl: APIurl + "PayrollAttendanceController.php",
attendanceUrl:APIurl + "getempattendance.php",
attendanceprocessUrl:APIurl + "EmpAttendanceHistoryController.php",
regularizationUrl: APIurl + "APIController.php?",
settingsgetUrl: APIurl + "HRSubscriptionCodeGetController.php",
settingsPostUrl: APIurl + "HRChangePasswordController.php?",
//sprintget
SprintgetUrl: APIurl + "SprintHeaderandDetailController.php",
SprintPPGetUrl: APIurl + "SprintProjectPlanGetController.php",
regGetUrl:APIurl + 'RegularizationGetController.php',
//payrollattendanceUrl: APIurl + "PayrollAttendanceController.php",
leavelApprovalUrl:  APIurl + "EmployeeRequestUpdateController.php",
requestAcknowledgeUrl:  APIurl + "LeaveRequest.php",
monthlyattendanceUrl:APIurl + "GetdatewiseEmpattendance.php",
biometricgetUrl:APIurl + "BioMetricConfigrationGetContoller.php",
biometricPostUrl:APIurl + "BioMetricConfigrationUpdateContoller.php",
partyBankUrl: APIurl + "PartyBankGetController.php",
partyBankPostUrl: APIurl + "PartyBankUpdateController.php",
partyContactgetUrl: APIurl + "PartyContractGetController.php",
partyContactPostUrl: APIurl + "PartyContractUpdateController.php",
settingsapprovalGetUrl: APIurl + "getcompanyapprovals.php",
settingsapprovalPOSTtUrl: APIurl + "postcompanyapprovals.php",
getLeaveweeklyDataUrl:APIurl +"LeaveWeeklyController.php",
timesheetattendanceUrl: APIurl +"DailyTaskgetController.php",
timesheetreportattendanceUrl: APIurl +"Dailytask_getController.php",
timesheetdtUrl: APIurl +"DailyTaskpostController.php",
empAttachmentUrl:baseurl +"EmployeeAttachmentsController.php",
empGetAttachmentUrl:APIurl +"getAttachmentsController.php",
getLeaveentryDataUrl:APIurl +"EmpLeaveConfigurationGetController.php",
geolocationgetUrl:APIurl + "EmpGeoLocationGet.php",
geolocationupdateUrl:APIurl + "EmpGeoLocationUpdate.php",
LeaveTypeurl: APIurl +"APIController.php",
subsNewUrl: APIurl +"SubscriptionPostController.php",
AssessmentAutoUrl: APIurl + "ScheduleAssessmentLookup.php",
InsightsUrl1: APIurl + "InsightGetController.php",
InsightsUrl2: APIurl + "InsightEmpPerformance.php",
ProjectCostingPDF: APIurl + "ProjectCostingReport.php",
ScheduleGetController: APIurl + "ScheduleGetController.php",
AppraisalScheduleGetcontroller: APIurl + "AppraisalScheduleGetcontroller.php",
Leadergeturl:  APIurl + "LeaderGetController.php",

};

export const getUrlSlice = createSlice({
  name: "globalurl",
  initialState,
  reducers: {},
});

export default getUrlSlice.reducer;
